// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wehexulgoxwswkaoygnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlaGV4dWxnb3h3c3drYW95Z254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzE1MTQsImV4cCI6MjA3MTY0NzUxNH0.twm3-dkHy-jerd0UGqsSh16cfyQYWxM2sJFM3nzcIME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});